
(() => {
  const $ = id => document.getElementById(id);
  const launcher=$('qaiLauncher'), shell=$('qaiShell'), close=$('qaiClose'), clear=$('qaiClear'), voiceReply=$('qaiVoiceReply'), messages=$('qaiMessages'), welcome=$('qaiWelcome'), thinking=$('qaiThinking'), input=$('qaiInput'), send=$('qaiSend'), mic=$('qaiMic'), recordState=$('qaiRecordState'), headerState=$('qaiHeaderState'), status=$('qaiStatus'), statusText=$('qaiStatusText'), toast=$('qaiToast'), contextText=$('qaiContextText');
  let history=[], busy=false, speakReplies=true, recorder=null, chunks=[], stream=null, currentAudio=null;

  function openAI(){shell.classList.add('active');launcher.classList.add('hidden');document.body.classList.add('ai-open');shell.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),700)}
  function closeAI(){shell.classList.remove('active');launcher.classList.remove('hidden');document.body.classList.remove('ai-open');shell.setAttribute('aria-hidden','true');stopAudio();if(recorder&&recorder.state==='recording')recorder.stop()}
  function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),5000)}
  function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
  function format(text){const lines=esc(text).split(/\r?\n/);let html='',list=false;for(const raw of lines){const line=raw.trimEnd(),m=line.match(/^\s*[-•]\s+(.+)/);if(m){if(!list){html+='<ul>';list=true}html+='<li>'+m[1]+'</li>';continue}if(list){html+='</ul>';list=false}html+=line.trim()?'<div>'+line+'</div>':'<br>'}if(list)html+='</ul>';return html.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>')}
  function addMessage(role,text){welcome.classList.add('compact');const wrap=document.createElement('div');wrap.className='qai-message '+role;const avatar=document.createElement('div');avatar.className='qai-msg-avatar';avatar.textContent=role==='user'?'YOU':'AI';const bubble=document.createElement('div');bubble.className='qai-bubble';bubble.innerHTML=format(text);wrap.append(avatar,bubble);messages.insertBefore(wrap,thinking);messages.scrollTop=messages.scrollHeight}
  function setThinking(v){thinking.classList.toggle('visible',v);headerState.textContent=v?'Reasoning about your request...':'Ready for text or voice';if(v)messages.scrollTop=messages.scrollHeight}
  function collectContext(){let latest=null;try{latest=JSON.parse(localStorage.getItem('qolda_latest_session')||'null')}catch{}contextText.textContent=latest?'Latest game report detected and ready for analysis.':'No detailed latest-session report detected. The AI will ask for missing measurements.';return{page:'QOLDA Neural Training Center',latest_session:latest,stored_best_scores:{adai:Number(localStorage.getItem('qolda_adai_phrase_best')||0),ornament:Number(localStorage.getItem('qolda_ornament_master_kids_best')||0)}}}
  async function health(){try{const r=await fetch('/api/health',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.configured)throw new Error();status.classList.add('online');statusText.textContent='Online';headerState.textContent='Ready for text or voice'}catch{status.classList.remove('online');statusText.textContent='Offline';headerState.textContent='AI server is not configured'}}
  async function sendMessage(explicit=null){const text=(explicit??input.value).trim();if(!text||busy)return;busy=true;input.value='';input.style.height='46px';addMessage('user',text);history.push({role:'user',content:text});setThinking(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:history.slice(-14),context:collectContext()})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'AI request failed');const answer=String(d.answer||'').trim();if(!answer)throw new Error('Empty AI response');addMessage('assistant',answer);history.push({role:'assistant',content:answer});if(speakReplies)speak(answer)}catch(e){console.error(e);addMessage('assistant','I could not reach the AI service. Check that qolda_ai_server.py is running and OPENAI_API_KEY is configured.');showToast(e.message||'AI service error')}finally{busy=false;setThinking(false)}}
  function stopAudio(){if(currentAudio){currentAudio.pause();URL.revokeObjectURL(currentAudio.src);currentAudio=null}if('speechSynthesis'in window)window.speechSynthesis.cancel()}
  async function speak(text){stopAudio();try{const r=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!r.ok)throw new Error();const blob=await r.blob(),url=URL.createObjectURL(blob);currentAudio=new Audio(url);headerState.textContent='Speaking...';currentAudio.onended=()=>{URL.revokeObjectURL(url);currentAudio=null;headerState.textContent='Ready for text or voice'};await currentAudio.play()}catch{if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(text);u.onstart=()=>headerState.textContent='Speaking...';u.onend=()=>headerState.textContent='Ready for text or voice';speechSynthesis.speak(u)}}}
  function mime(){return['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(t=>window.MediaRecorder&&MediaRecorder.isTypeSupported(t))||''}
  async function startRec(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){showToast('Voice recording is not supported in this browser.');return}try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});chunks=[];const m=mime();recorder=m?new MediaRecorder(stream,{mimeType:m}):new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=processRec;recorder.start(180);mic.classList.add('recording');recordState.classList.add('active');headerState.textContent='Listening...'}catch{showToast('Microphone access was not granted.')}}
  function stopRec(){if(recorder&&recorder.state==='recording')recorder.stop()}
  async function processRec(){mic.classList.remove('recording');recordState.classList.remove('active');headerState.textContent='Transcribing voice...';if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(!chunks.length){headerState.textContent='Ready for text or voice';return}try{const type=chunks[0].type||'audio/webm',blob=new Blob(chunks,{type}),ext=type.includes('mp4')?'m4a':'webm',form=new FormData();form.append('audio',blob,'qolda-voice.'+ext);const r=await fetch('/api/transcribe',{method:'POST',body:form}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Voice transcription failed');const t=String(d.text||'').trim();if(!t)throw new Error('No speech detected');input.value=t;headerState.textContent='Voice understood';await sendMessage(t)}catch(e){showToast(e.message||'Voice transcription failed');headerState.textContent='Ready for text or voice'}finally{chunks=[]}}

  launcher.addEventListener('click',openAI);close.addEventListener('click',closeAI);clear.addEventListener('click',()=>{history=[];messages.querySelectorAll('.qai-message').forEach(n=>n.remove());welcome.classList.remove('compact');stopAudio()});voiceReply.addEventListener('click',()=>{speakReplies=!speakReplies;voiceReply.classList.toggle('active',speakReplies);if(!speakReplies)stopAudio()});send.addEventListener('click',()=>sendMessage());input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,140)+'px'});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});mic.addEventListener('click',()=>recorder&&recorder.state==='recording'?stopRec():startRec());document.querySelectorAll('.qai-quick').forEach(b=>b.addEventListener('click',()=>sendMessage(b.dataset.prompt||b.textContent.trim())));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&shell.classList.contains('active'))closeAI()});collectContext();health();
})();
